app/models/user.rb
app/views/layouts/application.html.erb
config/environments/development.rb
config/routes.rb
db/migrate/20230515055222_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

I have craeted the model for User.
Please approve NOW!

Created user model

---

app/controllers/assassin/bookings_controller.rb
app/controllers/bookings_controller.rb
config/routes.rb
db/schema.rb
test/controllers/assassin/bookings_controller_test.rb
test/controllers/bookings_controller_test.rb

I changed the route to use the resource method
This will make it easier to nest routes in the future
additionally, I created the basic controller action for require actions.
However, Still need to fine tune to Params
The Params might not work at the moment.
We can work on this later.
I suggest to merge with master
because some of the pages will require each other to work.

Create bookings controller

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/assassin/bookings_controller.rb
app/policies/application_policy.rb
app/policies/assassin/booking_policy.rb
app/policies/assassin_policy.rb
app/policies/booking_policy.rb
db/schema.rb
test/policies/assassin/booking_policy_test.rb
test/policies/assassin_policy_test.rb
test/policies/booking_policy_test.rb

Added gem "pundit"
removed redundant gem in the gem list
added policies pages for each model
added Doug's comments from slack
** need to check code when building **

added pundit

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/views/layouts/application.html.erb
db/schema.rb

I updated the fonts we use, the primary color (red) and added the html & css for the banner.

Customize css

---

db/seeds.rb

Fixed code styling

---

app/assets/stylesheets/components/_card.scss
app/controllers/assassins_controller.rb
app/controllers/bookings_controller.rb
app/policies/assassin_policy.rb
app/policies/booking_policy.rb
app/views/assassins/show.html.erb
app/views/bookings/index.html.erb

I added in the "booking an assassin" table inside the show page.

Added booking an assassin table on show page

---

app/models/user.rb

Added relationship in the user
Where one user has one assassin
where one assassin has many bookings
where one user has many bookings as assassins
and 
User still can have many bookings as user

Fixed routing issue for Assassin Booking

---

app/controllers/assassin/bookings_controller.rb
app/controllers/bookings_controller.rb
app/models/user.rb
app/policies/assassin/booking_policy.rb
app/policies/booking_policy.rb
app/views/assassin/bookings/index.html.erb
config/routes.rb

The button to accept the Job is now completed
Routing works
Authorization fixed
assassin/booking_controller
added update action and related methods
booking_controller
align changes to strong params
user mode (see last pull)
assassin/booking_policy
added update? to allow for user to update if user is the owner of the assassin
VIEW HTML
assassin/bookings
fixed styling and formatting
added forms in place of the buttons

Button forms and routing is complete

---

app/controllers/bookings_controller.rb
app/views/assassins/show.html.erb

Modified the create method in the BookingsController - render path wasn't correct before

Fixed  BookingsController create method

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

modified:   app/assets/stylesheets/components/_navbar.scss
modified:   app/views/layouts/application.html.erb
new file:   app/views/shared/_navbar.html.erb

added navbar

---

app/controllers/assassin/bookings_controller.rb
app/controllers/assassins_controller.rb
app/views/assassin/bookings/index.html.erb
app/views/assassins/new.html.erb
config/routes.rb

Created the New assassin form
will redirect to assassin's booking.(blank if new)

created form to make new assassin

---

app/views/shared/_navbar.html.erb

Added Create new assassin link
if user has an assassin, it will become the see my assassins booking link

edit link to nav bar

---

app/models/booking.rb
app/views/assassin/bookings/index.html.erb

added assassin decline button and sorted

added assassin decline button and sorted

---

app/controllers/assassin/bookings_controller.rb
app/controllers/bookings_controller.rb
app/models/booking.rb
app/policies/booking_policy.rb
app/views/assassin/bookings/index.html.erb
app/views/assassins/index.html.erb
app/views/bookings/index.html.erb

Added routing of verify button
added picture proof

Update bookings page

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/controllers/pages_controller.rb
app/javascript/controllers/bookingform_controller.js
app/views/assassins/index.html.erb
app/views/assassins/new.html.erb
app/views/assassins/show.html.erb
app/views/layouts/application.html.erb

just css changes
and changed the route before login
(skipped login on landing page)

Display profile

---

app/views/assassin/bookings/index.html.erb

Gravity face profile picture inside assassin/bookings for the assassin.

gravity picture to face in Assassin/bookings

---

app/assets/stylesheets/components/_card.scss
app/views/assassin/bookings/_jobCard.html.erb
app/views/assassin/bookings/index.html.erb

Make Job cards into 3 section 
new jobs, active and history

Assassin booking sort view

---

app/assets/stylesheets/components/_card.scss
app/views/assassin/bookings/_jobCard.html.erb
app/views/bookings/_bookingCard.html.erb
app/views/bookings/index.html.erb

Change bookings view by category

Changed Bookings View

---

app/models/assassin.rb
app/views/assassin/bookings/index.html.erb
app/views/assassins/new.html.erb
app/views/assassins/show.html.erb
app/views/shared/_form.html.erb

Changed the button (of display) to "Make a request" from "IGNITE THE CONTRACT"
Changed the button (of the form) to "IGNITE THE CONTRACT"
Changed the label of submit in "Create Assassin"
Set the min. price of the form "Create Assassin" 
Add "optional" on uploading proof photo
Modified the assassin model >> validates .photo (must require a photo when creating new assassin)

bug fixed for new-assassin, changed button to make a request

---

app/views/assassin/bookings/_jobCard.html.erb

Added Option to Label and change to H3

Added optional and change h3

---

app/views/assassins/index.html.erb
app/views/shared/_navbar.html.erb

Change the corner profile pic so that if you own an assassin, the profile pic will become the picture of the assassin profile

added profile pic to nav bar if assassin

---

app/views/shared/_navbar.html.erb

Changed nav bar title "My assassin booking"
to "Contracts as assassin"

Changed nav bar naming. request review

---

app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

Changed it so that the logged in alert is message is not simply a <P> at the bottom of the page.
it is now a pop up alert, which u can exit.
additional styling required.

standard logged in message

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/assassin/bookings_controller.rb
app/controllers/assassins_controller.rb
app/controllers/bookings_controller.rb
app/models/booking.rb
app/policies/assassin_policy.rb
app/views/assassin/bookings/index.html.erb
app/views/assassins/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_profileCard.html.erb

Refractor the profile card
fixed the stimulus controller for the Booking form
fixed the edit profile page of assassin

fixed the routes and the form partial and the profile card

---

app/views/assassin/bookings/_jobCard.html.erb
app/views/bookings/_bookingCard.html.erb

Review box was lost after group pull today.
added it back

added the review box back

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/config/_colors.scss
app/javascript/controllers/display_bookings_controller.js
app/javascript/controllers/index.js
app/views/assassin/bookings/_jobCard.html.erb
app/views/assassin/bookings/_profileCard.html.erb
app/views/assassin/bookings/index.html.erb
app/views/bookings/_booking_map_for_assassins.html.erb

Change format of the assassin show page
3 button son top and can switch content

Format assassin bookings

---

app/views/assassin/bookings/index.html.erb

Added a reactive counter on the button

added job counter

---

app/controllers/assassin/bookings_controller.rb
app/controllers/assassins_controller.rb

fixed rating

---

app/views/bookings/_bookingCard.html.erb
app/views/bookings/_booking_map.html.erb
app/views/bookings/index.html.erb
app/views/pages/home.html.erb

fixed the booking card style

---

app/assets/stylesheets/config/_colors.scss
app/views/assassin/bookings/index.html.erb

button styling

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/config/_colors.scss
app/views/assassin/bookings/_jobCard.html.erb
app/views/assassin/bookings/index.html.erb

change btn collors

---

app/assets/stylesheets/components/_card.scss
app/views/assassin/bookings/index.html.erb

scrollable
